version: '3.8'

services:
  grudinhos:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - backend

  postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend

volumes:
  data:
    driver: local

networks:
  backend:
    driver: bridge
